default_platform(:ios)

platform :ios do
  desc "Lane to setup Anka VM for CI"
  lane :setup_anka do
    job_image_name = "#{ENV['ANKA_IMAGE_NAME']}-#{ENV['BUILDKITE_JOB_ID']}"

    begin
      sh("anka delete --yes #{job_image_name}")
    rescue => ex
      UI.message("No VM with #{job_image_name} exists.")
    end

    sh("anka clone #{ANKA_IMAGE_NAME} #{job_image_name}")
  end

  desc "Lane to cleanup Anka VM after CI"
  lane :cleanup_anka do
    job_image_name = "#{ENV['ANKA_IMAGE_NAME']}-#{ENV['BUILDKITE_JOB_ID']}"
    sh("anka delete --yes #{job_image_name}")
  end

  desc "Lane to run tests"
  lane :test do
    scan
  end
end
